# seed data

User.create(username: "bmaewood", password: "password", first_name: "Bailey", last_name: "Wood")
User.create(username: "pwerner", password: "password", first_name: "Peter", last_name: "Werner")

Artist.create(name: "Frank Ocean".upcase)
Artist.create(name: "Anderson .Paak".upcase)
Artist.create(name: "Chance the Rapper".upcase)
Artist.create(name: "Bon Iver".upcase)


Album.create(artist_id: 1, release_year: 2016, title: "Blonde".upcase)
Album.create(artist_id: 2, release_year: 2017, title: "Malibu".upcase)
Album.create(artist_id: 3, release_year: 2013, title: "Acid Rap".upcase)
Album.create(artist_id: 4, release_year: 2007, title: "For Emma, Forever Ago".upcase)
Album.create(artist_id: 3, release_year: 2019, title: "The Big Day".upcase)


Review.create(album_id: 1, user_id: 1, review_content: "My favorite Frank Ocean album", rating: 9.6)
Review.create(album_id: 2, user_id: 2, review_content: "Slaps!", rating: 9.8)
Review.create(album_id: 3, user_id: 2, review_content: "Maaaajor flames", rating: 8.9)
Review.create(album_id: 4, user_id: 1, review_content: "Emotional", rating: 7.4)
Review.create(album_id: 4, user_id: 2, review_content: "Solid", rating: 7.9)
Review.create(album_id: 5, user_id: 1, review_content: "Not his best :(", rating: 4.4)

Artist.create(name: "Lizzo".upcase)
Artist.create(name: "The Strokes".upcase)
Artist.create(name: "Fleetwood Mac".upcase)
Artist.create(name: "Kacey Musgraves".upcase) 
Artist.create(name: "Kanye West".upcase) 
Artist.create(name: "Mac Miller".upcase) 
Artist.create(name: "J. Cole".upcase) 
Artist.create(name: "YBN Cordae".upcase) 

Album.create(artist_id: 5, release_year: 2019, title: "Cuz I Love You".upcase)
Album.create(artist_id: 6, release_year: 2001, title: "Is This It".upcase)
Album.create(artist_id: 7, release_year: 1977, title: "Rumours".upcase)
Album.create(artist_id: 8, release_year: 2018, title: "Golden Hour".upcase)
Album.create(artist_id: 9, release_year: 2007, title: "Graduation".upcase)
Album.create(artist_id: 10, release_year: 2018, title: "Swimming".upcase)
Album.create(artist_id: 11, release_year: 2014, title: "Forrest Hills Drive".upcase)
Album.create(artist_id: 12, release_year: 2019, title: "The Lost Boy".upcase)

Review.create(album_id: 6, user_id: 1, review_content: "Str8 bangerz", rating: 8.9)
Review.create(album_id: 7, user_id: 1, review_content: "A classic", rating: 9.5)
Review.create(album_id: 8, user_id: 1, review_content: "Legend. Ary.", rating: 9.1)
Review.create(album_id: 9, user_id: 1, review_content: "Grammy's got it right", rating: 8.8)
Review.create(album_id: 10, user_id: 2, review_content: "Kanye's best album", rating: 9.3)
Review.create(album_id: 11, user_id: 2, review_content: "Poetic. RIP", rating: 8.9)
Review.create(album_id: 12, user_id: 2, review_content: "Unparalleled storytelling", rating: 9.1)
Review.create(album_id: 13, user_id: 2, review_content: "Complex cadences over soulful productions", rating: 9.2)
Review.create(album_id: 6, user_id: 2, review_content: "Really good!", rating: 8.5)
Review.create(album_id: 10, user_id: 1, review_content: "Luv this album", rating: 8.9)
Review.create(album_id: 2, user_id: 1, review_content: "Obsessed", rating: 9.2)
Review.create(album_id: 1, user_id: 2, review_content: "Need to listen again, sry", rating: 7.1)
